PhotoPrice: 1000.0 # Economy
CopyPrice: 100.0 # Economy
LoadCooldown: 60 # Seconds
MaxFileSize: 3072 # KiB
DefaultDownloadURL: 'https://i.imgur.com/NNvWR6B.png'
Rules: |-
  &6&lPhoto Rules
  &7> &fAll server rules apply to Photos!
  &7> &fNo &einappropriate&f content, including but not limited to
  &7> &f  &eviolence&f, &enudity&f, &edrug use&f, &einsults&f.
  &7> &fNo &eupsetting&f content, including but not limited to
  &7> &f  &ehorror&f, &eracism&f, &esexism&f, &epolitics&f, &ebigotry&f.
  &7> &fRules apply whether your Photo is &edisplayed&f or not.
  &7> &fViolations will result in a server &eban&f.
  &7> &fCavetale &eadmins&f decide what is or isn't appropriate.
