main: com.winthier.photos.PhotosPlugin
name: Photos

version: 0.1
api-version: 1.19

description: Load images onto maps
author: StarTux
website: https://github.com/StarTux/Photos

depend: [Core, SQL, PlayerCache, Money, Mytems]

commands:
  photo:
    aliases: [photos]
    description: Photos user interface
    usage: /photo
    permission: photos.photo
  photoadmin:
    aliases: [ photosadmin ]
    description: Admin interface
    permission: photos.admin
    usage: /photoadmin

permissions:

  photos.photo:
    description: Use the /photo command
    default: op

  photos.admin:
    description: Use /photoadmin
    default: op
