name: Photos
description: Load images onto maps
author: StarTux
version: 0.1
website: https://cavetale.com
main: com.winthier.photos.PhotosPlugin
commands:
  photo:
    aliases: [ photos ]
    description: Photos user interface
    usage: /<command>
    permission: photos.photo
photo:
  photos.photo:
    description: use the /photo and /photos command
    default: op
  photos.admin:
    description: advanced privileges for admins
    default: op
  photos.override.loadcooldown:
    description: Avoid the cooldown when loading urls
    default: op