name: Photos
description: Load images onto maps
author: StarTux
version: 0.1
api-version: 1.13
website: https://cavetale.com
main: com.winthier.photos.PhotosPlugin
commands:
  photo:
    aliases: [ photos ]
    description: Photos user interface
    usage: |-
      /photo load <URL>
      /photo name <NAME>
      /photo color <R> <G> <B>
      /photo color <COLOR>
    permission: photos.photo
  photoadmin:
    aliases: [ photosadmin ]
    description: Admin interface
    permission: photos.admin
    usage: |-
      /photoadmin list <player>
      /photoadmin create [id] - Create new Photo
      /photoadmin info <id> - Photo info
      /photoadmin transfer <id> [player] - Transfer ownership
      /photoadmin name <id> <name> - Change name
      /photoadmin load <id> <url> - Load URL
      /photoadmin color <id> <color> - Change color
      /photoadmin grant <player> - Give new Photo
      /photoadmin spawn <player> <id> - Give copy of Photo
      /photoadmin delete <id> - Delete Photo
photo:
  photos.photo:
    description: Use the /photo command
    default: op
  photos.admin:
    description: Use /photoadmin
    default: op
